-- +goose Up
CREATE TABLE IF NOT EXISTS jwt_rsa256_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "publicKey" text NOT NULL,
    "privateKey" text NOT NULL,
    "keyId" varchar(8) NOT NULL UNIQUE,
    "validUntil" timestamptz NULL,
    "isInvalid" boolean NOT NULL DEFAULT false,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION generate_key_id() RETURNS TRIGGER AS $$
BEGIN
    NEW."keyId" := RIGHT(ENCODE(DIGEST(NEW."publicKey", 'sha256'), 'hex'), 8);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_key_id ON jwt_rsa256_keys;
CREATE TRIGGER set_key_id
BEFORE INSERT ON jwt_rsa256_keys
FOR EACH ROW
EXECUTE FUNCTION generate_key_id();

-- +goose Down
DROP TRIGGER IF EXISTS set_key_id ON jwt_rsa256_keys;
DROP FUNCTION IF EXISTS generate_key_id;
DROP TABLE IF EXISTS jwt_rsa256_keys;
